### ISSUE TITLE
"attributes" property not updating on regions.

### ISSUE THREAD

**Issue by tslater** [ShiiRochi/wavesurfer-react#13]
I'm using the attributes property in order to set text on a region. It works in the initial render, but then won't update when I pass in new props. I was able to hack it locally, but can't find the components folder in this repo to make a PR.

## Before
```
  // TODO: may need some improvements
  useEffect(() => {
    if (regionRef) {
      let update = ["start", "end", "color", "data", "drag", "resize"].reduce(
        (result, prop) => {
          if (regionRef[prop] !== props[prop]) {
            return {
              ...result,
              [prop]: props[prop]
            };
          }

          return result;
        },
        {}
      );

      regionRef.update(update);
    }
  }, [
    props.start,
    props.end,
    props.color,
    props.data,
    props.resize,
    props.drag,
  ]);
```

## After
```
  // TODO: may need some improvements
  useEffect(() => {
    if (regionRef) {
      let update = ["start", "end", "color", "data", "drag", "resize", "attributes"].reduce(
        (result, prop) => {
          if (regionRef[prop] !== props[prop]) {
            return {
              ...result,
              [prop]: props[prop]
            };
          }

          return result;
        },
        {}
      );

      regionRef.update(update);
    }
  }, [
    props.start,
    props.end,
    props.color,
    props.data,
    props.resize,
    props.drag,
    props.attributes,
  ]);
```

**Comment by ShiiRochi** [comment]
@tslater Hello! First of all, thank you for the decision to contribute to the package! I've restored components, sorry, it is my fault. At a time, when I created this package I was not cared so much in keeping `master` in sync with published package version and in making all improvements in separate branches. Also, I have not been able to peacefully return to this package for a long time, thus I will have a time to rethink it.

From now on you can create PR.

**Comment by tslater** [comment]
No worries. I was just a little confused. Thanks for all your work! I'll go ahead and send over that PR.

**Comment by tslater** [comment]
Thanks again for your quick response. Here is the PR: https://github.com/ShiiRochi/wavesurfer-react/pull/14

**Comment by ShiiRochi** [comment]
@tslater, you can now use `2.0.6` version of `wavesurfer-react`. It may take some time for NPM to update the registry completely, thus local projects could indicate that package has been updated.

**Comment by tslater** [comment]
That was fast! Thanks!
