### ISSUE TITLE
Error message on demo: Warning: Failed prop type: Invalid prop `plugins[0]` supplied to `WaveSurfer`, expected a ReactNode.

### ISSUE THREAD

**Issue by tslater** [ShiiRochi/wavesurfer-react#15]
I'm getting this same error message locally...the plugin still works fine, but I'm trying to get 0 errors/warning and this is polluting the console. I'd love to know if there is something I'm doing wrong. I tried to follow the demo, but it has the same error.
This is the demo I'm referring to (linked on the ReadMe):
https://codesandbox.io/s/wavesurfer-react-20-gqvb6?from-embed

![image](https://user-images.githubusercontent.com/449326/110081208-d33c6500-7d48-11eb-8fcf-0db6dc1c7d89.png)

**Comment by ShiiRochi** [comment]
If everything works, then it's more chance to be a mistake in proptypes definition. I'll later.

**Comment by ShiiRochi** [comment]
Hi, @tslater. I've just published 2.0.7 version of the package, try it. As soon as I can see on fork of demo codesandbox, error is gone.

**Comment by denizdogan** [comment]
Funny, I just came across this exact same problem and you just released the fix :) Thanks @ShiiRochi

**Comment by tslater** [comment]
@ShiiRochi  Thanks for fixing that!!!! Looks like it is working for me!
