### ISSUE TITLE
Additional Option Support

### ISSUE THREAD

**Issue by teophilus** [ShiiRochi/wavesurfer-react#2]
Hey, Great job porting this into a react component, I'm trying to use some additional options ie:
https://wavesurfer-js.org/example/rounded-bars/index.html can we work together to acheive this? I haven't had time to jump into the code but I can possibly take a look tomorrow and make a PR.

**Comment by teophilus** [comment]
Maybe we can just spread the props so we can account for any prop that the original wavesurfer.js adds

**Comment by ShiiRochi** [comment]
@teophilus, thanks for the contribution and wish to help. I saw your changes and I think that props spreading is very risky, because we would have to guarantee that no unwanted props would go into waveForm options `...props`.

For example, we implemented some _**option A**_, that would need some **_prop A_**, but we accidentally forgot to ignore it inside _render_ method, thus it would go into waveForm options with `...props`.

I would prefer not to use `...props` until it is really necessary.

**Comment by ShiiRochi** [comment]
From my point of view, _rounded-bars_ should be described as an additionally available prop.

**Comment by teophilus** [comment]
Hey! Thanks for getting back to me. 
I agree `...props` isn't always the best solution so I'll make a new PR taking your considerations in mind give me a couple of hours.

**Comment by teophilus** [comment]
Quick question would you be open to to using `prop-types`? 
https://reactjs.org/docs/typechecking-with-proptypes.html

**Comment by ShiiRochi** [comment]
> Quick question would you be open to to using `prop-types`?
> https://reactjs.org/docs/typechecking-with-proptypes.html

It's ok

**Comment by ShiiRochi** [comment]
As soon as your first attempt failed, can you write down all the wave form available props?

**Comment by ShiiRochi** [comment]
@teophilus, I think we should just describe options without setting default values to all of them because for the clear start, the only id is required.

**Comment by teophilus** [comment]
> @teophilus, I think we should just describe options without setting default values to all of them because for the clear start, the only id is required.

I think you might be right! I was getting too many error with my attempt at defaults and type safety.


P.S. Here is the list of options for safe keeping:
```
            audioRate,
            audioContext,
            audioScriptProcessor,
            autoCenter,
            backend,
            backgroundColor,
            barGap,
            barHeight,
            barRadius,
            barWidth,
            closeAudioContext,
            container,
            cursorColor,
            cursorWidth,
            fillParent,
            forceDecode,
            height,
            hideScrollbar,
            interact,
            loopSelection,
            maxCanvasWidth,
            mediaControls,
            mediaType,
            minPxPerSec,
            normalize,
            partialRender,
            pixelRatio,
            plugins,
            progressColor,
            removeMediaElementOnDestroy,
            renderer,
            responsive,
            scrollParent,
            skipLength,
            splitChannels,
            waveColor,
            xhr,
```

**Comment by ShiiRochi** [comment]
@teophilus, package has been updated to 1.1.0 with that feature aboard. You can now pass additional options the following way:
```jsx
<WaveForm
       progressColor="red"
       barWidth={3}
       barRadius={3}
       barGap={3}
       cursorWidth={1}
       height={200}
>
    {regions.map(regionProps => (
        <Region
            onUpdateEnd={console.log}
            key={regionProps.id}
            {...regionProps}
        />
    ))}
/WaveForm>
```

**Comment by teophilus** [comment]
> @teophilus, package has been updated to 1.1.0 with that feature aboard. You can now pass additional options the following way:
> 
> ```js-jsx
> <WaveForm
>        progressColor="red"
>        barWidth={3}
>        barRadius={3}
>        barGap={3}
>        cursorWidth={1}
>        height={200}
> >
>     {regions.map(regionProps => (
>         <Region
>             onUpdateEnd={console.log}
>             key={regionProps.id}
>             {...regionProps}
>         />
>     ))}
> /WaveForm>
> ```
> 
> About typings, most possibly I will use TypeScript as soon as my IDE works great with it.

Awesome! I really appreciate it!

**Comment by tslater** [comment]
@ShiiRochi any updates on getting TypeScript types?
