### ISSUE TITLE
Support for Markers?

### ISSUE THREAD

**Issue by sujitsagar** [ShiiRochi/wavesurfer-react#20]

**Comment by ShiiRochi** [comment]
> 

Any description about the matter or a link?

**Comment by sujitsagar** [comment]
Sorry for not this earlier.

Wavesurfer now has Markers support in the `waveform`. Can you add wrapper to it?
`https://wavesurfer-js.org/example/markers/index.html
`

**Comment by ShiiRochi** [comment]
@sujitsagar, as I can see, markers is passed into `plugins` field in creator, thus, it can be considered as a internal plugin of WaveSurfer. Try to pass it into `plugins` like so:
```
const plugins = [
  {
    plugin: WaveSurfer.markers,
    options: {
      markers: [
        {
          time: 5.5,
          label: "V1",
          color: '#ff990a'
        },
        {
          time: 10,
          label: "V2",
          color: '#00ffcc',
          position: 'top'
        }
      ]
    }
  },
  // some other stuff
];
```

**Comment by sujitsagar** [comment]
That's awesome. It worked, ShiiRochi. 

Thank you so much. Closing this issue.
