### ISSUE TITLE
Region onDoubleClick not working.

### ISSUE THREAD

**Issue by KushaanKapoor** [ShiiRochi/wavesurfer-react#22]
Hey! I wanted to use the double click functionality of the Region Plugin but I wasnt able to. 
in the Region component of your package, there's this 1 slight error. 

in Region.js, on Line 89,
(0, _useRegionEvent.default)(regionRef, "dbclick", onDoubleClick);

it should be dblclick instead.

I hope you can take out your time to fix this as that would be really helpful!

Thanks.

**Comment by ShiiRochi** [comment]
@KushaanKapoor, thanks for an issue! I will try to fix it as soon as possible. Also, if you would have a time you can easily fix it on your own via corresponding PR, so it could be very helpful.

**Comment by KushaanKapoor** [comment]
created a PR!

**Comment by ShiiRochi** [comment]
@KushaanKapoor, hello, I've merged your PR #23 and published the package under the `2.0.9` version.
