### ISSUE TITLE
Hiding the cursor/progressline

### ISSUE THREAD

**Issue by eriksachse** [ShiiRochi/wavesurfer-react#29]
Hello, 
it seems that I can't hide the little line that shows the progress. I tried it with the vanilla version and it is `cursorColor = "transparent"` or `hideCursor = true`. All other options work
<img width="129" alt="Screenshot 2021-11-10 at 08 35 59" src="https://user-images.githubusercontent.com/24212703/141069892-c1886115-e2b0-4077-b5d9-5bc8d61b0f57.png">
.

**Comment by ShiiRochi** [comment]
Hi, @eriksachse, sorry for long-delayed response, but it is working. You can try in demo codesandbox, just use `2.0.11` version of the package. Both of the two properties mentioned by you are enlisted inside watched props list.
```
      <WaveSurfer plugins={plugins} onMount={handleWSMount}>
        <WaveForm id="waveform" hideCursor cursorColor="transparent">
          {regions.map((regionProps) => (
            <Region
              onUpdateEnd={handleRegionUpdate}
              key={regionProps.id}
              {...regionProps}
            />
          ))}
        </WaveForm>
        <div id="timeline" />
      </WaveSurfer>
```

**Comment by ShiiRochi** [comment]
@eriksachse, any progress?

**Comment by eriksachse** [comment]
@ShiiRochi I'll get to this ASAP, currently working on something different.

**Comment by ShiiRochi** [comment]
I am closing this issue, because of no response.
