### ISSUE TITLE
Using wavesurfer-react with local (not in server) audio files

### ISSUE THREAD

**Issue by Mlallena** [ShiiRochi/wavesurfer-react#31]
Hi!

I have long been working on a website where I could show an audio file waveform, and WaveSurfer seems to be the best option I've seen so far.

However, I'm having a bit of trouble in trying to adapt this to my work. I am trying to make a site with two simple parts, one that lets the user load a local file and another that shows the audio waveform (there will be other functions later). However, when I try to send the data as an URL to the system (the same way I do with other players, such as react-h5-audio-player, it returns an error because it considers the url is empty.

Do you have a suggestion on how to do this? (Basically, it would be the demo you've got on codesandbox.io, but instead of an audio at the server folder, it'd be an audio in a computer opening the website and loading a local file)

**Comment by ShiiRochi** [comment]
Hmm, it seems that this question is more for `waveform.js` community, but I will try to share some ideas.

But before show will go on, please take into account, that I could take your idea not very properly.

From my point of view...you should load a file via file input, then take it from `value` of that input and save it as Blob or some other stuff in some global store or where it is comfortable to access and theeen create an URL to that Blob, that is cached by browser. Created URL you are passing to waveform's `load` method (you will need waveform instance for that), so it would load a file from browser cache and play it.

**Comment by ShiiRochi** [comment]
Sorry, but I will close this issue as soon as there is no response.
