### ISSUE TITLE
Support for Markers as well as Regions

### ISSUE THREAD

**Issue by mo-seph** [ShiiRochi/wavesurfer-react#33]
It would be nice to support Markers as well as Regions in a similarly elegant style.

**Comment by ShiiRochi** [comment]
Hi, sorry for late response, will try to look at it ASAP

**Comment by ShiiRochi** [comment]
@mo-seph, now you can use `Marker` component. Please, take into account current possibilities wavesurfer provides us with to do with markers. If you can improve realization of marker component your PR is welcomed.
