### ISSUE TITLE
Hello,

### ISSUE THREAD

**Issue by ytmsuhsff** [ShiiRochi/wavesurfer-react#42]
Hello, I installed wavesurfer JS audio wave display, but the wave loading speed is very slow. You need to save the wave to the database to load the wave quickly. Is it possible to solve this problem.
(wavesurfer.js https://wavesurfer-js.org/ )

Just like them
https://icons8.com/music/search/beach
https://tunetank.com/tracks/

This is my website
http://www.partymusic.cn/

我的邮件 [304955091@qq.com](mailto:304955091@qq.com)

**Comment by ShiiRochi** [comment]
I think this question is more related to the native library team.

Delay until waves becomes visible depends on a variety of factors:
1. accuracy and detail of waves
2. network bandwidth
3. audio duration
4. width of player

So, storing waves into a JSON files or a database can just save your time assuming that one audio can be opened more than once.

Wavesurfer decodes your audio if no waves are provided, but it really can take some time to be completed, so you can make a server to generate waves from an audio at the time of uploading or downloading...using performant languages, that can do that task really fast.

**Comment by ytmsuhsff** [comment]
Hello, brother, I want to know how to store the waveform in JSON file or database. Can you do it? The wave on my website is loaded directly, so the loading is very slow

**Comment by ShiiRochi** [comment]
Hi, I don't have time to do some aside stuff, but if you don't mind, then I would rather help just with an advice. You know, there is a soviet film that is called "Through thorns to the stars" (it's a direct translations) and I think that doing stuff you need by yourself you will gain more experience and knowledges, than just asking others to do it instead.
