### ISSUE TITLE
Typescript errors

### ISSUE THREAD

**Issue by bknill** [ShiiRochi/wavesurfer-react#44]
I just added the library into my project with the sample code and it's throwing a load of Typescript errors:

On WaveSurfer
`This JSX tag's 'children' prop expects a single child of type 'Element', but multiple children were provided.ts(2746)`

Because I added the timeline div

And 

```
Type '{ children: never[]; id: string; hideCursor: true; cursorColor: string; }' is not assignable to type 'IntrinsicAttributes & WaveFormProps'.
  Property 'hideCursor' does not exist on type 'IntrinsicAttributes & WaveFormProps'
```

**Comment by haswalt** [comment]
@bknill This is a change in React 18 to remove children from the default props list. Downgrade your project to react 17.

**Comment by ShiiRochi** [comment]
@bknill, can you please a sandbox with such behaviour? I migrated to TS and updated packages in a local demo to the following:
```
"dependencies": {
    "polate-js": "^1.0.6",
    "react": "18.1.0",
    "react-dom": "18.1.0",
    "react-scripts": "^5.0.1",
    "styled-components": "^5.3.5",
    "uuid": "^3.3.3",
    "wavesurfer-react": "^2.1.4",
    "wavesurfer.js": "^6.2.0"
  },
  "devDependencies": {
    "typescript": "^4.6.4"
  },
``` 

And I'm not seeing any TS related errors.

**Comment by ShiiRochi** [comment]
@bknill, hello, please try version `2.1.6` of the package
