### ISSUE TITLE
prop-type dependency

### ISSUE THREAD

**Issue by anyasinyavskaya** [ShiiRochi/wavesurfer-react#47]
Hi
prop-type package seems to be deprecated and maybe broken (according to https://www.npmjs.com/package/prop-type)
do you really need this package in dependencies? why?

**Comment by ShiiRochi** [comment]
@anyasinyavskaya, hi! Thank you for reminding me about this. It seems, that in typescript migration PR I forgot to remove `prop-type` package. Human factor. Will be fixed in the near future.

**Comment by ShiiRochi** [comment]
@anyasinyavskaya, `prop-types` is removed in version `2.1.4`

**Comment by ShiiRochi** [comment]
UPD: also removed import of that package in `2.1.5`
