### ISSUE TITLE
I can't fire events

### ISSUE THREAD

**Issue by Simoneth** [ShiiRochi/wavesurfer-react#52]
Hi,
I tried to fire events as:

```
     useEffect(() => {
        wavesurferRef.current.on("finish", () => {
            console.log("Track Finished");
          });
      }, []); 
```

It doesn't work, it doesn't fire when a song is finished. 
Is it my fault?

**Comment by ShiiRochi** [comment]
@Simoneth, hi, did you try to check whether other events are being fired?

**Comment by Simoneth** [comment]
> @Simoneth, hi, did you try to check whether other events are being fired?

Hmm...it's strange, I can fire "audioprocess" but not "finish" and I have no idea why.
This is my function to start play, maybe it's related (I use regions):

```
   wavesurferRef.current.play(
      regionsRef.current[id].start,
      regionsRef.current[id].end
    );
```

**Comment by ShiiRochi** [comment]
So, you can subscribe to "audioprocess" event and it's working, but it does not work with "finished", don't you? 

If that is so, then event subscription through wavesurfer instance is working, however `finished` event is not being fired for some reason that is, from my POV, `wavesurfer.js` related.

**Comment by ShiiRochi** [comment]
@Simoneth, I've tried to listen for "finish" event in demo fork. 

The result is that this event if called when record playing is fully completed, it is not related to region or region play, because all you do to play region is just like make wavesurfer to play record's fragment, when "finish" is related to record. 

It should also be taken into account, that the end of an audio can differ from the end of a region, so even if there would be a difference in a pair of milliseconds, then "finish" can be not fired...but this is just my assumption.

**Comment by Simoneth** [comment]
> @Simoneth, I've tried to listen for "finish" event in demo fork.
> 
> The result is that **this event is called when record playing is fully completed**, it is not related to region or region play, because all you do to play region is just like make wavesurfer to play record's fragment, when "finish" is related to record.
> 
> It should also be taken into account, that the end of an audio can differ from the end of a region, so even if there would be a difference in a pair of milliseconds, then "finish" can be not fired...but this is just my assumption.

From Regions plugin page, I can't find any event that could fire the end of the region play...any workaround? It's just for my toggle button "Play / Stop"

**Comment by ShiiRochi** [comment]
@Simoneth, I think, that this question (how to listen to _region play completed_ or simulate it) is more related to `wavesurfer.js` repository. From my point of view, you can add new listener for...an audioprocess or progress, but with explicit aim to call some callback when progress will reach regions end...I will provide you with some pseudo code, but the rest is fully up on you:
```
function callbackFn () {
    ...some code...
} // or useCallback...

const callbackRef = useRef(callbackFn);

function playRegion ({ start, end, ...restOfRegion }) {
    ws.current.on("progress", (data) => {
        if (data === end) {
            // it will save you from referencing issues
            callbackRef.current();
        }
    });

    ws.current.play(
      start,
      rend
    );
}
```

**Comment by Simoneth** [comment]
Here my simple solution:

```
    useEffect(() => {
        wavesurferRef.current.on("region-out", () => {
            console.log("Track Finished");
        });
    }, [regions]); 
```
