### ISSUE TITLE
Waveform customisation

### ISSUE THREAD

**Issue by NinjaCoderDotCom** [ShiiRochi/wavesurfer-react#58]
Hi, 
How can i pass all the options ( [https://wavesurfer-js.org/docs/options.html](https://wavesurfer-js.org/docs/options.html) ) available for wavesurfer.js into the wavesurfer-react to change the waveform according to my requirements?

**Comment by ShiiRochi** [comment]
Hi, @NinjaCoderDotCom! If you will pass'em via `WaveForm` component (old-way), they will be selected from it with `getWaveFormOptionsFromProps`, so look at code of this utility function to see, what you can pass. You can also pass props via `WaveSurfer` component.

Currently, only plugins are updated on updates. Feature for other updatable fields is not ready yet.

**Comment by NinjaCoderDotCom** [comment]
Sure. Thanks @ShiiRochi
