### ISSUE TITLE
Can not get zoom to work

### ISSUE THREAD

**Issue by braime** [ShiiRochi/wavesurfer-react#59]
Hi there, great package! Hope it is okay to raise an issue for this, because it is more a question:
**Is it currently possible to zoom into the waveform?**
I could not get it to work, I tried in the handler method of a slider:

`wavesurferRef.current.zoom = value  `

or something like

```
<WaveSurfer  zoomLevel={valueFromState}>
<WaveSurfer  zoom={valueFromState}>
```

Sadly no luck so far. If it is possible, could you please nudge me in the right direction or even provide a working example? I am building on top of the live Demo https://codesandbox.io/s/wavesurfer-react-20-gqvb6  (which is currently not working, right?)

Thanks in advance!

**Comment by ShiiRochi** [comment]
Hello! You should use wavesurfer instance and then call it's `zoom` method.
https://wavesurfer-js.org/api/class/src/wavesurfer.js~WaveSurfer.html#instance-method-zoom

**Comment by braime** [comment]
Thanks for the answer! I think I get the theory and got it working in a seperate react-vanilla js version, where I just import it like this
`import WaveSurfer from 'wavesurfer.js';`
then in componentDidMount do 
`this.waveform = WaveSurfer.create({ ... });`
finally in the handler 
`handleChange = (event) => {
    this.waveform.zoom(event.target.value);
  };`

But how do I get access to the wavesurfer instance when using your package? I thought `wavesurferRef.current` would be the instance, but it seem to have no zoom method (at least that is the error in the sliders handler method). Do I need to additionally import it like above from the wavesurfer.js library? Can you please give me one more hint?

**Comment by ShiiRochi** [comment]
Watch the demo, I made there a button to change zoom

**Comment by braime** [comment]
Thank you very much for the fast help and even providing an example! It is working now fine in the slider and the problem was me doing:
`wavesurferRef.current.zoom = value ` instead of `wavesurferRef.current.zoom(value)` :see_no_evil:

Shall I close the issue?

**Comment by ShiiRochi** [comment]
@braime, thanks for the response, if your case has been solved, you may close it
