### ISSUE TITLE
"Cannot use import statement outside a module" with Next.js 

### ISSUE THREAD

**Issue by nvminhhieu** [ShiiRochi/wavesurfer-react#64]
I follow/copy the Sandbox example into my Next.js 13.2.1, and it returns me the error "Cannot use import statement outside a module". I also tried import a single `<WaveSurfer/> ` only but same error.

**Comment by ShiiRochi** [comment]
Hi! Try to look at https://github.com/ShiiRochi/experimental-next-project.

**Comment by nvminhhieu** [comment]
Thanks! Using dynamic import from `next/dynamic` and wrap outside component using the package seems to work! 

```tsx
//index.ts
import dynamic from 'next/dynamic'

const MusicPlayer = dynamic(() => import('@/components/MusicPlayer/MusicPlayer'), {
    ssr: false,
})
...
return(
<MusicPlayer />
)
...

//MusicPlayer.ts
...
return(
<WaveSurfer onMount={handleWSMount}>
    <WaveForm
        responsive
        id="waveform"
        cursorColor="transparent"
    ></WaveForm>
</WaveSurfer>
)
```

However, it would be nice if this is being documented on README as well!

**Comment by ShiiRochi** [comment]
It is more related to NextJS specific to run pages code both server-side and client-side. Thus any package that depends on browser code and is not compiled to be nodejs friendly, should be imported as dynamic.
