### ISSUE TITLE
getCurrentTime without triggering too much re-render on the Component

### ISSUE THREAD

**Issue by nvminhhieu** [ShiiRochi/wavesurfer-react#65]
By following this approach https://github.com/wavesurfer-js/wavesurfer.js/issues/753#issuecomment-229721073, I managed to show the current elapsed time. Then I assign the value to a state to display on the UI. 

```ts
const [currentTime, setCurrentTime] = useState(0)

const handleWSMount = (waveSurfer: any) => {
        wavesurferRef.current = waveSurfer
        if (wavesurferRef.current) {
            wavesurferRef.current.load('/test.mp3')

            wavesurferRef.current.on('ready', () => {
                setDuration(wavesurferRef.current.getDuration())
            })

            //Show current time
            wavesurferRef.current.on('audioprocess', function () {
                //ISSUE: THIS MAKE COMPONENT RE-RENDERING
                setCurrentTime(wavesurferRef.current.getCurrentTime())
            })

        }
    }
}
return <>{currentTime}</>
...
```

However, the `wavesurfer.on('audioprocess'...` triggers so many times, which results in `setCurrentTime` updates too much, and makes the component re-render redundantly. Is there a way to get the current time that can avoid this behavior?

**Comment by ShiiRochi** [comment]
You have at least 3 options.

### I. React.Context
You can create ProgressProvider that would render two contexts:
- ProgressSetterProvider
- ProgressValueProvider

I think their naming explicitly tells you what to do further with'em.

### II. Subscriptions and Outer State Management
You can either create custom observable mechanism to subscribe to it, or use module like `zustand` or any other state module you want that moves state management out of react component life-cycle.

### III. Value Debouncing
You can use something like `use-denounce` module to either denounce value, or callback function, or if your requirement is just to show hours and seconds and no milliseconds, then you can use useState and check inside callback whether integer part changed or not.

**Comment by nvminhhieu** [comment]
Thank you for the suggestion! You are right, since I just need the seconds, I figure that I can `Math.floor` the time, and `setState()`. It's even easier because React `setState` only trigger state changes if the value is being changed. 
```tsx
wavesurferRef.current.on('audioprocess', function () {
    setCurrentTime(Math.floor(wavesurferRef.current.getCurrentTime()))
})
```
