### ISSUE TITLE
Is it possible to use this with Tauri / NextJS SSG?

### ISSUE THREAD

**Issue by serg06** [ShiiRochi/wavesurfer-react#66]
As mentioned in the [Tauri guide](https://tauri.app/v1/guides/getting-started/setup/next-js/):

> To make Next.js work with Tauri we are going to use the SSG mode since it generates only static files that can be included in the final binary.

I tried using the solution in https://github.com/ShiiRochi/wavesurfer-react/issues/64 but it just doesn't render anything at all.

Is it possible?

**Comment by ShiiRochi** [comment]
`wavesurfer-react` depends on `wavesurfer.js`. It's better to check whether all native code of the latter is usable server-side. I did't dive deep in SSG, but from my POV, to support it, there (in `wavesurfer.js`) should be drawing step, hydration step and running step, which, I think, are not the basic blocks of `wavesurfer.js`, where currently all code is drawing and working at the same time in one step.

Also, someone could **try** to create a plugin for `wavesurfer.js` to add SSG support.

**Comment by ShiiRochi** [comment]
I closed this issue, because it is not related directly to `wavesurfer-react` module
