### ISSUE TITLE
generating new markers in component wrapped by <StrictMode> not rendering new markers

### ISSUE THREAD

**Issue by micascheid** [ShiiRochi/wavesurfer-react#67]
I used the sandbox example in which I made the following modification:

function AudioPlayer()... // previously was-> function App()
.
.
.
export default AudioPlayer; // previously was...
//const rootElement = document.getElementById("root");
//ReactDOM.render(<App />, rootElement);

I then use the AudioPlayer Component as a child component which the parent component is wrapped by <StrictMode>

simply put:
<StrictMode>
     <AudioPlayer />
<StrictMode>
doesn't allow for newly generated markers to render to the screen. If I remove strictmode wrapping then the newly created markers render just fine. 

Clearly I'm not understanding something about the rendering process under Strictmode. 
Any thoughts on what I may need to change in order to still continue using strictmode and render newly created markers?

Thanks for any help!

**Comment by micascheid** [comment]
here is what I do in my index.js:

const container = document.getElementById("root");
const root = createRoot(container); // createRoot(container!) if you use TypeScript
root.render(
  <StrictMode>
    <AudioPlayer />
  </StrictMode>
);

The above doesn't render newly created markers. If I remove <StrictMode> then it does render newly created markers.
I'm using react 18.2

**Comment by ShiiRochi** [comment]
Hi, @micascheid! If still relevant, then check, please, a demo below, I surrounded App component with `StrictMode` and it seems that everything works as expected.

https://codesandbox.io/p/sandbox/wavesurfer-react-2-0-forked-dsvj93?file=%2Fsrc%2Findex.js%3A330%2C1

**Comment by micascheid** [comment]
My apologies for my complacency. As I see and have used today. All is working well. Thanks for closing it.
