### ISSUE TITLE
Support content for regions

### ISSUE THREAD

**Issue by tslater** [ShiiRochi/wavesurfer-react#70]
The Wavesurfer examples show content in regions:
https://wavesurfer.xyz/examples/?regions.js

Would love if that could work here.

**Comment by ShiiRochi** [comment]
Hello, @tslater! Did you try to pass content alongside with other regions' data? Did it work?

**Comment by ShiiRochi** [comment]
@tslater, check please, version 3 of `wavesurfer-react`.

**Comment by ShiiRochi** [comment]
@tslater I will close issue due to the fact that V3 is considered to have such functionality
