### ISSUE TITLE
Support for wavesurfer.js 7+

### ISSUE THREAD

**Issue by alecvn** [ShiiRochi/wavesurfer-react#71]
From my testing `wavesurfer-react` only works up to `wavesurfer.js` version `6.6.4`, but isn't compatible with versions `7.0.0` and up.

Has there been any work done to support the new major version or is it perhaps being planned?

**Comment by ShiiRochi** [comment]
Hi! Thank you for the issue, I hope I will get soon to it and will add a support for v7

**Comment by ShiiRochi** [comment]
I created separate branch for version 3 of wavesurfer-react (#72)

**Comment by ShiiRochi** [comment]
@alecvn, today I published `wavesurfer-react@^3.0.0`, you can now adjust your codebase according to new README. I will try to provide migration guid in a few days when I will have enough time to write.

i will update demo link in a few minutes.

**Comment by alecvn** [comment]
Amazing @ShiiRochi! Thank you so much for the hard work!
