### ISSUE TITLE
audio load issue

### ISSUE THREAD

**Issue by tweetsydotio** [ShiiRochi/wavesurfer-react#75]
normal html audio can load the link as audio (https://www.listennotes.com/e/p/a5ae21acf75a43538b635cf6b089f0b3)
but wavesurferRef.current.load("https://www.listennotes.com/e/p/a5ae21acf75a43538b635cf6b089f0b3"); can not handle

**Comment by ShiiRochi** [comment]
Hi, @tweetsydotio, **wavesurfer-react** uses native **wavesurfer** methods under the hood. If you see that wavesurfer cannot do something, then it would be better ask within wavesurfer repo.

**Comment by ShiiRochi** [comment]
I'm gonna close it for now as not planned. You can search for a solution in wavesurer.js repository
