### ISSUE TITLE
codesandbox code issue

### ISSUE THREAD

**Issue by tweetsydotio** [ShiiRochi/wavesurfer-react#76]
https://www.loom.com/share/4b04ef6ac3d247f8ae92b0dfbcfda097?sid=c419fc50-fc46-408c-8333-40a4abcc1b3f
could you please some suggestion to solve the issue

**Comment by ShiiRochi** [comment]
Hi, @tweetsydotio, seems to be some problem when components are destroyed when doing redirect, can you produce some kind of sandbox that I can look through?

**Comment by ShiiRochi** [comment]
@tweetsydotio, I created local next.js project and found out that in dev env useEffect was called twice, thus we had two instances of wavesurfer, regions was connected to first one, that was actually removed, thus when you try to move to another page, they called unexisted methods.

Check version `wavesurfer-react@^3.0.2`
