### ISSUE TITLE
Multiple Instances of <Waveform />

### ISSUE THREAD

**Issue by teophilus** [ShiiRochi/wavesurfer-react#9]
@ShiiRochi congrats on v2! - I just got back from the Holiday and i'm ready to hack on this a little more.

Quick question since this defaults to `id="waveform"` on the DOM how do we create multiple instances?

**Comment by ShiiRochi** [comment]
@teophilus, thanks. You can pass `id` prop to WaveForm component. It sets `id` attr and at the same time is used to construct `container` waveform option

**Comment by teophilus** [comment]
Ah! makes sense, I thought it would of been a little more involved than that. - Thanks!
