### ISSUE TITLE
Issue with changing the style of the waveform scrollbar

### ISSUE THREAD

**Issue by MosiQt** [ShiiRochi/wavesurfer-react#92]
I was trying to change the style of the waveform stylesheet and I was unable to do that even by changing form the global css. Is there any solution for this:
![image](https://github.com/ShiiRochi/wavesurfer-react/assets/53909162/d2d525f1-a423-4037-8de6-d36ab18643e9)

**Comment by ShiiRochi** [comment]
You need to stick to waveforms repository to find out how to style wavesurfer
